import test from "node:test";
import assert from "node:assert/strict";
import { normalizeModelTurn, parseLegacyToolIntent, partiallyVerifiedAllowed, validateRemoteToolCall } from "../agent-tool-protocol.mjs";
import { canonicalRunResult } from "../run-results-runtime.mjs";
test("normalizes native tool calls without exposing argument text", () => { const turn = normalizeModelTurn({ content: "I'll check", tool_calls: [{ id: "c1", function: { name: "run_remote_command", arguments: '{"command":"pwd"}' } }] }, { executionContext: true }); assert.equal(turn.text, ""); assert.equal(turn.toolCalls[0].arguments.command, "pwd"); assert.equal(turn.source, "native"); });
test("recognizes only bounded exact legacy execution JSON", () => { assert.equal(parseLegacyToolIntent('```json\n{"action":"run","command":"pwd"}\n```', { executionContext: true })[0].arguments.command, "pwd"); assert.equal(parseLegacyToolIntent('Example: {"action":"run","command":"pwd"}', { executionContext: true }), null); assert.equal(parseLegacyToolIntent('{"action":"run","command":"pwd"}', { executionContext: false }), null); assert.equal(parseLegacyToolIntent('{"action":"run","command":"pwd","evil":true}', { executionContext: true }), null); });
test("validates tool arguments and partial status", () => { assert.equal(validateRemoteToolCall({ name: "run_remote_command", arguments: { command: "pwd" } }).valid, true); assert.equal(validateRemoteToolCall({ name: "run_remote_command", arguments: null }).code, "INVALID_TOOL_ARGUMENTS"); assert.equal(partiallyVerifiedAllowed(Array(10).fill(0).map(() => ({ status: "pending" }))), false); assert.equal(partiallyVerifiedAllowed([{ status: "passed" }, { status: "pending" }]), true); });
test("hosting detection is one bounded permission-aware probe", () => { const checked = validateRemoteToolCall({ name: "detect_hosting_environment", arguments: { domain: "ogzensmm.online" } }); assert.equal(checked.valid, true); assert.match(checked.value.command, /\/usr\/local\/cpanel/); assert.match(checked.value.command, /uapi/); assert.doesNotMatch(checked.value.command, /systemctl|apt-get|yum|dnf/); });
test("zero acceptance evidence is never partially verified", () => { const result = canonicalRunResult({ requestedStatus: "running", acceptance: Array(10).fill(0).map((_, i) => ({ key: `c${i}`, status: "not_tested", evidence: [], required: true })) }); assert.equal(result.status, "FAILED"); assert.equal(result.passed, 0); });
